name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version number
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        run: docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN}}

      - name: Build plugin and push
        run: |
          cd plugin
          ./build-all.sh $TAG

      - name: Build hook
        run: |
          cd hook
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o flannel-network-plugin-hook
          chmod +x flannel-network-plugin-hook

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: hook/flannel-network-plugin-hook
          body: "Release of flannel-network-plugin-hook version ${{ env.TAG }}"
          draft: false
          prerelease: false
